import MainLayout from "@/components/Layout";
import ThemeProvider from "@/components/ThemeProvider";
import "@/styles/globals.scss";
import "@/styles/fonts.scss";
import IntlWrapperProvider from "@/utils/intlWrapperProvider";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <IntlWrapperProvider>
        <ThemeProvider>
          <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <MainLayout>   <Component {...pageProps} /></MainLayout>
        </ThemeProvider>
      </IntlWrapperProvider>
    </>
  );
}
